### ISSUE TITLE
How to Set Registers for Time Averaging

### ISSUE THREAD

**Issue by msi-matthew** [brettmarl/node-ina219#3]
According to the Adafruit forum, "The INA219's internal math engine will to simple filtering by taking the average of multiple readings. You can set the value using the configuration register" (https://forums.adafruit.com/viewtopic.php?f=8&t=130072).

According to the TI data sheet (section 8.6.2.1), this is possible by changing bits 3 -6 for shunt averaging, and bits 7 - 10 for Bus Averaging (http://www.ti.com/lit/ds/symlink/ina219.pdf).

This behavior appears to be supported in this module with the `ina219.writeRegister(register, value, callback)` function.

How would I set the bus averaging to 12 bits?

How would I set the shunt averaging to 128 samples over 68.10 ms?

I get this error when I run the following code:

> TypeError: callback is not a function

```
// Set BADC Bus ADC Resolution/Averaging
// ina219.writeRegister(7, 0)  // 9-bit resolution
// ina219.writeRegister(8, 0)  // 10-bit resolution
// ina219.writeRegister(9, 0)  // 11-bit resolution
ina219.writeRegister(10, 1)    // 12-bit resolution

// SADC Shunt ADC Resolution/Averaging
// 128 Samples 68.10 ms
ina219.writeRegister(3, 1)
ina219.writeRegister(4, 1)
ina219.writeRegister(5, 1)
ina219.writeRegister(6, 1)

ina219.calibrate32V1A(() => {
  ina219.getBusVoltage_V((volts) => {
     console.log("Voltage: " + volts);
  })
})
```

**Comment by brettmarl** [comment]
The error you are getting is because you aren't passing a callback. Ideally the code should work without a callback - especially given that it's using write2I2cBlockSync and no longer goes aysnc... it's kind of a relic of the first async version. 

To get your code working pass "function(){}" for the third parameter, eg:

ina219.writeRegister(7, 0, function(){})  // 9-bit resolution

**Comment by msi-matthew** [comment]
Great. Thank you!!
